### ISSUE TITLE
controlled_animation is not found 

### ISSUE THREAD

**Issue by santoshgistto** [RanfiCD/widget_recorder#1]
`import 'package:simple_animations/simple_animations/controlled_animation.dart';` is not found

**Comment by RanfiCD** [comment]
Hi!

simple_animations is a different package and has nothing to do with widget_recorder.

If you are having this issue when trying to run the example, you have to add simple_animations to your project like in the "pubspec.yaml" file located inside the "example" folder.

**Comment by santoshgistto** [comment]
thanks @RanfiCD  my bad i didn't see pubspec file.

Another question: is it possible to save as video format ?

**Comment by RanfiCD** [comment]
@santoshgistto I'm afraid that video manipulation is out of the scope of this widget.

However, widget_recorder provides you with images in the form of binary data that you can then manipulate as you wish. You could, for example, use a package (such as [video_manipulation](https://pub.dev/packages/video_manipulation)) to generate the video from the images you have taken.

**Comment by rdcoder33** [comment]
> @santoshgistto I'm afraid that video manipulation is out of the scope of this widget.
> 
> However, widget_recorder provides you with images in the form of binary data that you can then manipulate as you wish. You could, for example, use a package (such as [video_manipulation](https://pub.dev/packages/video_manipulation)) to generate the video from the images you have taken.

How many images does it take in a second? I mean what would be the possible frame-rate of the video?

**Comment by RanfiCD** [comment]
@rdcoder33 The delay between snapshots is up to you to decide. However, the more often you take a snapshot, the more resources it will consume. So you have to find a balance that suits your use case.
